import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import client from "../sanity-client";

export default function Home(props) {
  const { post } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.grid}>
        {post?.map((onePost, idx) => (
          <a
            key={onePost._id}
            href={`post/${onePost.slug.current}`}
            className={styles.card}
          >
            <h2>{onePost.title} &rarr;</h2>
            {onePost.title}
          </a>
        ))}
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps(context) {
  // It's important to default the slug so that it doesn't return "undefined"

  const post = await client.fetch(
    `
    *[_type == "post" ]
  `
  );
  return {
    props: {
      post,
    },
  };
}
